### ISSUE TITLE
Verify that we can `git push` from the publishing pipeline

### ISSUE THREAD

**Issue by f-f** [purescript/registry-dev#213]
Right now we run the `API` CI pipeline on issues and issue comments - we should verify that from there we are able to authenticate and `git push` to:
- this `registry` repo itself
- and the `registry-index` repo

The best way to test this would be from some dummy repos, rather than doing it here (i.e. everyone can test this on their own repos)

**Comment by f-f** [comment]
I think a basic proof of concept of this would be to have:
- a workflow that starts from opening an issue
- and that commits one file and pushes it to the main branch of the same repo it's contained in

**Comment by YanikCeulemans** [comment]
As mentioned in the call, I'll do some research on this and report any progress I make in this issue.

**Comment by YanikCeulemans** [comment]
It seems that there already is an action in the github actions marketplace which pushes to a protected branch using a token and a user name: https://github.com/marketplace/actions/push-to-a-protected-branch This action just runs the following shell script: https://github.com/colmose/push-bot/blob/main/entrypoint.sh

**Comment by YanikCeulemans** [comment]
There is also https://github.com/marketplace/actions/github-commit-push which combines commit and push using a github token with the added benefit that it supports pushing to a different repo. This would support pushing to the `registry-index` repo.

**Comment by YanikCeulemans** [comment]
> I think a basic proof of concept of this would be to have:
> 
> * a workflow that starts from opening an issue
> * and that commits one file and pushes it to the main branch of the same repo it's contained in

This is now fully functional in my test repo: https://github.com/YanikCeulemans/gh-actions-playground

To proceed we probably want to be able to push to a different repo after doing a git checkout i presume? This would support the second scenario where we would want to push to the `registry-index`

**Comment by f-f** [comment]
@YanikCeulemans this is great! :clap: 

A constraint that we didn't consider yesterday is the fact that the main branch is protected - I wonder if we can still push to it?

> To proceed we probably want to be able to push to a different repo after doing a git checkout i presume? This would support the second scenario where we would want to push to the `registry-index`

And yes, we should make sure that everything pretty much works before trying to port this approach to here

**Comment by YanikCeulemans** [comment]
@f-f I've tested pushing to a protected branch and can confirm the push gets rejected.

I've seen in repo settings however that you can allow force pushes to protected branches. If this were setup in the registry repo, we could modify the Github action to use a force push and bypass the protected branch check.

If you would rather not allow force pushes, we would probably have to look for (or create) a Github action which would open a PR containing the changes.

**Comment by f-f** [comment]
I think we'd be fine with force-pushes from administrators, which is why we are using a token from @pacchettibotti, which is part of the @purescript/packaging team and has access to this

**Comment by YanikCeulemans** [comment]
@f-f I've enabled the force push option in my `gh-actions-playground` repo action to test whether or not it would work. It seems that it does not work with the default settings and I'm not completely sure why. My first guess is that the user that the action uses by default:
```
author_email: github-actions[bot]@users.noreply.github.com
author_name: github-actions[bot]
```
doesn't have the required permissions to force push to the master branch. The output from the action isn't completely clear on that though:
```
Run actions-js/push@master
  with:
    github_token: ***
    force: true
    branch: master
    author_email: github-actions[bot]@users.noreply.github.com
    author_name: github-actions[bot]
    directory: .
Started: bash /home/runner/work/_actions/actions-js/push/master/start.sh
Push to branch master
[master 459de74] chore: autopublish 2021-10-03T10:57:08Z
 1 file changed, 1 insertion(+)
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access. 
```
I'm going to try and use my email and name for the config options and see if that changes anything. As owner of the repo I can push to the master branch without the `--force` option.
